name: Check code formatting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: apt-get update
        run: sudo apt-get update

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check formatting
        run: ./.github/tools/check_code_formatting_all.sh
